### PR TITLE
bug fixes for razorpay redirection wc-api

### PR DESCRIPTION
**Pull request by prem-techchefs**
Bug fix for github issue #150 #149 #148

### CODE REVIEW

**Comment by ChetanGN** [comment]
@thediveshsharma will definitely help to resolve this issue. Can you please let us know which Razorpay Woocommerce plugin version you are using? Have you modified anything in the plugin code? Because we observed after payment its returning 200 success response status, and it's printing 1 in redirection page which may be because of `die()` or `exit` function (if you had modified the code). 
If you can provide us your clone site or test server credentials by creating the support ticket [here](https://razorpay.com/support/#), then it would be helpful for us to debug this particular issue.

**Comment by thediveshsharma** [comment]
As per my knowledge I didn't modify the plugin code whatsoever. I just
installed the plugin as it is and the issue started arising..
I am using a paid theme by whiskers , maybe its happening because of their
codes in the theme. They have stopped providing support for the theme now.
So I can't even contact them .
Here are all the details you need .
1) https://whiskers.cmsmasters.net/pet-store/ (Theme I am using)
2) Wordpress 5.5
3) Razorpay for woocommerce version 2.5.0
4) Woocommerce version 4.4.1

I am okay if you use my main login ID and password.

Login :- riopetshop786@gmail.com
Pass :- rio@009977

**Comment by thediveshsharma** [comment]
I have already created a new issue on github with details regarding my issues plus I have opened a support ticket too {support ticket number (87984) }
https://github.com/razorpay/razorpay-woocommerce/issues/164
Link to my issues

**Comment by ChetanGN** [comment]
@thediveshsharma can you please try to make the payment using any of the default themes?

**Comment by thediveshsharma** [comment]
> @thediveshsharma can you please try to make the payment using any of the default themes?

Tried with Twenty Seventeen theme and its working fine. No issues with payments. Check this [screenshot](https://ibb.co/ThfTG8N) for proof.

This issue arising because of theme only , any way to solve it? I don't want to remove this theme because I have paid for it .

I have created a staging login for your reference too
Here's the login credentials.
Link :- https://riopetshop.in/1598249513703/wp-login.php
ID :- test 
password :- test 

Please help me!

**Comment by ChetanGN** [comment]
@thediveshsharma This issue is nothing to do with your current theme. There is one plugin conflicting with the Razorpay woocommerce plugin, So I just disabled it in your stage environment. Now it's working fine. Can you please check and let us know.

**Comment by thediveshsharma** [comment]
> @thediveshsharma This issue is nothing to do with your current theme. There is one plugin conflicting with the Razorpay woocommerce plugin, So I just disabled it in your stage environment. Now it's working fine. Can you please check and let us know.

Damn ! Working fine now. Thank you soo much sir <3 . Issue is solved now. Was worried from last 2 days. Thank you for helping me.

**Comment by ChetanGN** [comment]
> > @thediveshsharma This issue is nothing to do with your current theme. There is one plugin conflicting with the Razorpay woocommerce plugin, So I just disabled it in your stage environment. Now it's working fine. Can you please check and let us know.
> 
> Damn ! Working fine now. Thank you soo much sir <3 . Issue is solved now. Was worried from last 2 days. Thank you for helping me.

You're welcome @thediveshsharma

**Pull request closed without merging**
